### ISSUE TITLE
Support for IPv6

### ISSUE THREAD

**Issue by OxySynth** [dopeghoti/SF-Tools#3]
I have to access and run the server over IPv6 because of DS-Lite and Carrier-Grade NAT. I would like to use this tool to check my API connectivity because it seem IPv6 support is currently broken and the server just can't access the API.
I have tried the 64 bit prefix-len global address and the local address, I get the following error when running 
`
 python3 sfcheck.py fe80::be24:11ff:fee9:5f2b
`

`Traceback (most recent call last):
  File "/home/steam/SatisfactoryTest/SF-Tools/sfcheck.py", line 141, in <module>
    main(host, port, verbose)
  File "/home/steam/SatisfactoryTest/SF-Tools/sfcheck.py", line 106, in main
    response = probeServer( address, port )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steam/SatisfactoryTest/SF-Tools/sfcheck.py", line 55, in probeServer
    UDPClientSocket.sendto( msgToServer, ( srvAddress, srvPort ) )
socket.gaierror: [Errno -9] Address family for hostname not supported`

**Comment by dopeghoti** [comment]
You can try altering line 54 of `sfcheck.py` to say `family=AF_INET6` rather than `family=AF_INET` to see if that works in your case.  Give it a try, and if it works I will add an option to explicitly test using IPv6.

**Comment by dopeghoti** [comment]
@OxySynth actually, I went one better.  When you have time, check out the `IPv6` branch, and give it a few tests.  My IPv6 connectivity at home is, at best, dodgy, but I was able to test it a couple times successfully.  Give it a go and if it seems to work, I'll merge it into `main`.
